# Generated by Django 3.0.5 on 2020-11-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='pic.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(default='update your number', max_length=10, null=True),
        ),
    ]
